In [5]:
import numpy as np

# Now you can use NumPy functions and objects
arr = np.array([4, 2, 3, 4, 5])
print(arr)

[4 2 3 4 5]


In [10]:
zeros = np.zeros((2, 6))     # 2x3 array of 0s
ones = np.ones((3, 2))       # 3x2 array of 1s


print("Zeros:\n", zeros)
# print("Ones:\n", ones)

Zeros:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [21]:
range_arr = np.arange(1, 10, 1) 
print("Range Array:", range_arr)

Range Array: [1 2 3 4 5 6 7 8 9]


In [24]:
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [25]:
arr = np.array([1, 2, 3, 4])

# Arithmetic operations (element-wise)
print(arr + 5)   # [6 7 8 9]
print(arr * 2)   # [2 4 6 8]
print(arr ** 2)

[6 7 8 9]
[2 4 6 8]
[ 1  4  9 16]


In [26]:
b = np.array([10, 20, 30, 40])
print(arr + b) 

[11 22 33 44]


In [30]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # 10
print(arr[1:4])    # [20 30 40]
print(arr[-1]) 

10
[20 30 40]
50


In [33]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix[0, 1])   # 2
print(matrix[:, 2])   # [3 6]


2
[3 6]


In [39]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

result = arr1 + arr2
print(result)  # [False False  True  True  True]

[ 20  40  60  80 100]


In [40]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

condition = x < y
where_result = np.where(condition, x, y)
print(where_result)  # [1 2 3]

[1 2 3]
